- name: Install nginx
  hosts: all
  become: yes
 
  tasks: 
  - name: Nginx Installation 
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Service start
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
