- name: play level variables
  hosts: local
  connection: local 
  vars:
    Name: "Ruthvik"
    Age: "24"
    Weight: "80"

  tasks: print variables
  ansible.builtin.debug:
  msg: " Hello, my name is{{Name}}, age is {{Age}} and i weigh {{Weight}} kilos"